SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: AdvEnt_CL_Pre_defined
NUM_WORKERS: 7
ANTI_CL: False
TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv2
  RESTORE_FROM: ./../../experiments/snapshots/Predefined_1_view/model_17.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  SAVE_PRED_EVERY: 2000
  CLASSES_INCLUDE: 19
  WEIGHTS: False
  INIT_ITER: 0
  PREV_STOP: 0
  INCLUDE_NEW: 25000
  BATCH_SIZE_SOURCE: 2
  BATCH_SIZE_TARGET: 2
TEST:
  MODE: best
  SNAPSHOT_STEP: 2000
  SNAPSHOT_MAXITER: 36000
