SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: Curriculum_include_every_epoch_learning_rate_adapted
NUM_WORKERS: 6
ANTI_CL: False
TRAIN:
  DA_METHOD: CL
  MODEL: DeepLabv2
  RESTORE_FROM: ./../../experiments/snapshots/Curriculum_include_every_epoch_learning_rate_adapted/model_1150000.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  EARLY_STOP: 4000000
  MAX_ITERS: 8000000
  SAVE_PRED_EVERY: 12500
  CLASSES_INCLUDE: 19
  WEIGHTS: False
  INIT_ITER: 1150001
  PREV_STOP: 1150000
  INCLUDE_NEW: 25000
  BATCH_SIZE_SOURCE: 1
  ORDER: Marginal
TEST:
  MODE: single
  SNAPSHOT_STEP: 1075000
  SNAPSHOT_MAXITER: 1500000
