SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: CL_maxsquare_consistency
NUM_WORKERS: 4
ANTI_CL: False
TRAIN:
  DA_METHOD: maxsquare
  MODEL: DeepLabv2
  RESTORE_FROM: ./../pretrained_models/558MIOU.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best
