SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: AntiCL_maxsquare_TRAINED
NUM_WORKERS: 4
ANTI_CL: False
TRAIN:
  DA_METHOD: maxsquare
  MODEL: DeepLabv2
  RESTORE_FROM: ./../pretrained_models/Anti_CL.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
TEST:
  MODE: best
