SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: MINENT_baseline
NUM_WORKERS: 6
ANTI_CL: False
TRAIN:
  DA_METHOD: MinEnt
  MODEL: DeepLabv2
  RESTORE_FROM: ./../../experiments/snapshots/Source_longer/model_1.pth
  MULTI_LEVEL: True
  LAMBDA_ADV_MAIN: 0.001
  LAMBDA_ADV_AUX: 0.0002
  INIT_ITER: 0
  SAVE_PRED_EVERY: 2000
  CLASSES_INCLUDE: 19
  WEIGHTS: False
  PREV_STOP: 0
  BATCH_SIZE_SOURCE: 2
  BATCH_SIZE_TARGET: 2
TEST:
  MODE: single 
  SNAPSHOT_STEP: 2000
  SNAPSHOT_MAXITER: 120000
  FLIP: True
  RESTORE_FROM: 
    - /mnt/rhome/rac/ADVENT/experiments/snapshots/MINENT_baseline/model_96000.pth
  
