SOURCE: GTA
TARGET: Cityscapes
EXP_NAME: Source_longer
NUM_WORKERS: 6
ANTI_CL: False
TRAIN:
  DA_METHOD: Source_only
  MODEL: DeepLabv2
  RESTORE_FROM: ./../pretrained_models/DeepLab_resnet_pretrained_imagenet.pth
  MULTI_LEVEL: True
  EARLY_STOP: 33700
  MAX_ITERS: 67400
  CLASSES_INCLUDE: 2
  WEIGHTS: False
  INIT_ITER: 0
  PREV_STOP: 0
  ORDER: Pre_defined
  INPUT_SIZE_SOURCE: 
    - 640
    - 360
  LEARNING_RATE: 0.0005
  BATCH_SIZE_SOURCE: 3
TEST:
  MODE: best
  SNAPSHOT_STEP: 1
  SNAPSHOT_MAXITER: 1500000
